repos:
  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0  # Use the latest stable version
    hooks:
      - id: hadolint
        name: Hadolint Linter
        entry: hadolint
        language: system
        files: '.*Containerfile.*'

