#!/bin/sh
#
# _profile: The `/etc/profile` file provides system-wide environment variables. This
#           script loads base environment variables for ALL containers and calls
#           container specific variables. Order is maintained using the alphabetical
#           order of the symlinks in `/etc/profile.d/`
#
#
# author: adam@gautier.org
# date: 2022-11-16
# component: environment
#
# - - - - - - - - - - - - - - - - - - - - - - -

alias osversion='cat /etc/alpine-release'

log() {
 DEBUG="[D]"
 INFO="[I]"
 WARN="[W]"
 ERROR="[E]"
 
 TIMESTAMP="$(/bin/date '+%h %d %H:%M:%S')"
 LEVEL="$DEBUG"
 OPTION=$1
 case ${OPTION} in
  -e) LEVEL="$ERROR"
  ;;
  -w) LEVEL="$WARN"
  ;;
  -i) LEVEL="$INFO"
  ;;
  -d) LEVEL="$DEBUG"
  ;;
esac

COMPONENT="$2"
MSG="$3"
LOG_MSG="$TIMESTAMP container $COMPONENT:$LEVEL-$MSG"
echo $LOG_MSG
}


