#!/usr/bin/env python

"""
This is a simple script to fetch the latest Alpine Linux Latest Stable Version and prints to
stdout
"""

import requests
import sys

def main(arch="aarch64"):
    HEAD = "alpine-base-"
    TAIL = ".apk"
    URL = "https://dl-cdn.alpinelinux.org/alpine/latest-stable/main/%s/" % arch
    response = requests.request('GET', URL)
    content = "%s" % response.content
    content = content[content.find(HEAD):]
    content = content[:content.find(TAIL)+len(TAIL)]
    version = content.split("-")[2]
    return version
    
if __name__ == "__main__":
    try:
        arch = "aarch64"
        if 2 == len(sys.argv):
            machine = sys.argv[1]
        print(main(arch=arch))
        sys.exit(0)
    except Exception as e:
        print( e , sys.stderr)
        print( "0.0.0" )
        sys.exit(1)
    
