#!/usr/bin/env python

# authentication-check: This python script attempts to *GET* the provided url.  This script does not provide a client certificate
#                        for authentication which means that it should fail when pointed to the endpoint URL. To use:
#                        `authentication-check URL`

import requests # https://requests.readthedocs.io/en/latest/
import sys

HTTP_SUCCESS_MIN = 200
HTTP_SUCCESS_MAX = 299
assert 2 == len(sys.argv), "Invalid parameters"
url = sys.argv[1]
response = requests.get(url, allow_redirects=False)
code = response.status_code 
if HTTP_SUCCESS_MIN <= code <= HTTP_SUCCESS_MAX: 
 print("[FAIL] URL endpoint(%s) returned a successful response code(%s)"  % (url, code))
 sys.exit(code)
else:
 print("[SUCCESS] URL endpoint(%s) does not support anonymous users" % url)  
 sys.exit(0)

