#!/bin/sh
#
# backup: This script defines the default backup mechanism function and should be overloaded by downstream controls

echo "[ INFO] Current directory($(/bin/pwd))"
echo "[ INFO] Container backup script"
/bin/cp -rv /mnt/volumes/container/* /tmp/backup
echo "$(date +%s)" > /tmp/backup/.date
return $?
