version: "3.9"
services:
  alpine:
    build:
      args:
        CONTAINER_VERSION: "3.19.0"
        ALPINE_VERSION: "3.19.0"
      context: .
      dockerfile: container.build
      no_cache: true
      tags:
        - "alpine:build"
        - "gautada/alpine:build"
        - "gautada/alpine:latest"
    image: "alpine:build"
    hostname: alpine
    container_name: alpine
    ports:
      - "8888:8080"
    volumes:
      - "Container:/mnt/volumes/container"
      - "Backup:/mnt/volumes/backup"
      - "Configmaps:/mnt/volumes/configmaps"
      - "Secrets:/mnt/volumes/secrets"
      
volumes:
  Container:
    external: true
    name: "Container"
  
  Backup:
    external: true
    name: "Backup"

  Configmaps:
    external: true
    name: "Configmaps"

  Secrets:
    external: true
    name: "Secrets"



