version: "3.9"
services:
  alpine:
    build:
      args:
        ALPINE_VERSION: "3.17.2"
      context: .
      dockerfile: Containerfile
      no_cache: true
      tags:
        - "alpine:build"
    image: "gauta/build:dev"
    environment:
      - SYSTEM_ENVIRONMENT=DEVELOPMENT
    hostname: alpine
    ports:
      - "8080:8080"
    volumes:
      - "container:/mnt/volumes/container"
      - "backup:/mnt/volumes/backup"
        
volumes:
  container:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/volumes/container
  backup:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/volumes/backup
      
