version: "3.9"
services:
  alpine:
    build:
      args:
        CONTAINER_VERSION: "3.18.0"
        ALPINE_VERSION: "3.18.0"
      context: .
      dockerfile: container.build
      no_cache: true
      tags:
        - "alpine:dev"
        - "gautada/alpine:dev"
    image: "alpine:dev"
    hostname: alpine
    ports:
      - "8888:8080"
    volumes:
      # - "/Users/mada/Workspace/Container:/mnt/volumes/container"
      # - "/Users/mada/Workspace/Backup:/mnt/volumes/backup"
      - "/mnt/volumes/container/Workspace/Container:/mnt/volumes/container"
      - "/mnt/volumes/container//Workspace/Backup:/mnt/volumes/backup"
#         
# volumes:
#   container:
#     driver: local
#     driver_opts:
#       type: none
#       o: bind
#       device: /mnt/volumes/container
#   backup:
#     driver: local
#     driver_opts:
#       type: none
#       o: bind
#       device: /mnt/volumes/backup
      
