#!/bin/sh
#
# container-backup
#
# Controller script for container wide back-up

ENCRYPTION_KEY="/etc/backup/encryption.key"
KEY_FINGERPRINT="$(gpg --show-keys $ENCRYPTION_KEY | sed -n '2p' | xargs)"
if [ "" == "$(gpg --list-keys)" ] ; then
 gpg --trusted-key $KEY_FINGERPRINT --import $ENCRYPTION_KEY
else
 gpg --list-keys
fi

BACKUP_TAG="$(date +%H)"
FOLDER_WORKING="/var/backup"
FOLDER_CACHE="/tmp/backup"
FOLDER_BACKUP="/opt/backup"

cd $FOLDER_WORKING
# Execute the container backup function
container_backup
cd /

# Clear all but the latest chain
duplicity remove-all-but-n-full 1 --force file://$FOLDER_BACKUP

FILE_MANIFEST=$FOLDER_BACKUP/duplicity-full.*.manifest.gpg
# SET BACKUP CHAIN
if [ ! -f $FILE_MANIFEST ] ; then
 duplicity full --encrypt-key F637FEA3CEFBF0B21DBEE9E6585A99256A092267 --archive-dir $FOLDER_CACHE $FOLDER_WORKING file://$FOLDER_BACKUP
else
   # RESET BACKUP CHAIN - At midnight
 if [ "00" == "$(date +%H)" ] ; then
  duplicity full --encrypt-key F637FEA3CEFBF0B21DBEE9E6585A99256A092267 --archive-dir $FOLDER_CACHE $FOLDER_WORKING file://$FOLDER_BACKUP
 else
  TIMESTAMP_LAST=$(date +%s -r $FILE_MANIFEST)
  TIMESTAMP_NOW=$(date +%s)
  TIMESTAMP_DAY=86400
  TIMESTAMP_DELTA=$(($TIMESTAMP_NOW-$TIMESTAMP_LAST))
  # RESET BACKUP CHAIN - If older than 24 hours
  if [ $TIMESTAMP_DAY -lt $TIMESTAMP_DELTA ] ; then
   duplicity full --encrypt-key F637FEA3CEFBF0B21DBEE9E6585A99256A092267 --archive-dir $FOLDER_CACHE $FOLDER_WORKING file://$FOLDER_BACKUP
  else # INCREMENTAL BACKUP
   duplicity incr --encrypt-key F637FEA3CEFBF0B21DBEE9E6585A99256A092267 --archive-dir $FOLDER_CACHE $FOLDER_WORKING file://$FOLDER_BACKUP
  fi
 fi
fi
