#!/bin/ash
#
# [ENTRYPOINT](https://docs.docker.com/engine/reference/builder/#entrypoint) is the default
# initial process which and executes all the applications and services that run in a container.
#
# This is the default ENTRYPOINT located at `/usr/sbin/entrypoint` and should be 
# augmented when used in downstream containers by over writting the `/etc/container/entrypoint` 
# file (which by default is a symlink to `/mnt/volumes/container/entrypoint`
#

ENTRYPOINT_PARAMS="$@"
. /etc/profile

log "-i" "entrypoint" "Start alpine($(osversion)-$(/usr/bin/whoami))"


log "-i" "entrypoint" "Start crond"
/usr/bin/pgrep crond > /dev/null
TEST=$?
if [ $TEST -eq 1 ] ; then
 if [ "$SYSTEM_ENVIRONMENT" = "DEVELOPMENT" ] ; then
   /usr/bin/sudo /usr/sbin/crond -b -l 0 -L /var/log/crond
   RTN=$?
 else
  /usr/bin/sudo /usr/sbin/crond -b -l 0 -L /dev/stdout
  RTN=$?
 fi
 if [ $RTN -ne 0 ] ; then
  log "-i" "entrypoint" "Application (crond) failed to start"
  return 3
 fi
else
 log "-e" "entrypoint" "Application(crond) already started"
 return 2
fi
/usr/bin/pgrep crond > /dev/null
RTN=$?
if [ $RTN -ne 0 ] ; then
 log "-e" "entrypoint" "Application (crond) failed to start"
 return 4
fi

. /etc/container/entrypoint
if [ "$SYSTEM_ENVIRONMENT" = "DEVELOPMENT" ] ; then
 log "-e" "entrypoint" "Launch application as detatched"
 app_entrypoint ENTRYPOINT_PARAMS >> /mnt/volumes/container/_log 2>&1 &
 exec $ENTRYPOINT_PARAMS
else
 log "-e" "entrypoint" "Launch blocking application"
 app_entrypoint ENTRYPOINT_PARAMS
fi
