version: "3.9"
services:
  alpine:
    dns:
      - 10.0.4.200
      - 10.0.4.201
    build:
      args:
        ALPINE_VERSION: "3.17.2"
      context: .
      dockerfile: Containerfile
      no_cache: true
      tags:
        - "alpine:dev"
    image: "alpine:dev"
    environment:
      - SYSTEM_ENVIRONMENT=DEVELOPMENT
    hostname: alpine
    ports:
      - "8080:8080"
    volumes:
      - "container:/mnt/volumes/container"
      - "backup:/mnt/volumes/backup"
        
volumes:
  container:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/mada/Workspace/alpine/container-volume
  backup:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/mada/Workspace/alpine/backup-volume
      
