kind: pipeline
type: exec
name: CICD - Alpine Container

platform:
  os: linux
  arch: arm64

steps:

- name: build
  commands:
  - /usr/bin/podman-compose build --no-cache
  
- name: test
  commands:
  - echo "No tests are defined at this time."
  - podman login --username=$DOCKERIO_USERNAME --password=$DOCKERIO_PASSWORD docker.io
  - podman tag $(/usr/bin/compose-service):build docker.io/$DOCKERIO_USERNAME/$(/usr/bin/compose-service):test
  

- name: integrate
  environment:
    CONTAINER_VERSION: 3.17.0
    DOCKERIO_USERNAME:
      from_secret: username.docker.io
    DOCKERIO_PASSWORD:
      from_secret: password.docker.io
  commands:
  - podman login --username=$DOCKERIO_USERNAME --password=$DOCKERIO_PASSWORD docker.io
  - podman tag $(/usr/bin/compose-service):build docker.io/$DOCKERIO_USERNAME/$(/usr/bin/compose-service):latest
  - podman push docker.io/$DOCKERIO_USERNAME/$(/usr/bin/compose-service):latest
  - podman tag $(/usr/bin/compose-service):build docker.io/$DOCKERIO_USERNAME/$(/usr/bin/compose-service):$CONTAINER_VERSION
  - podman push docker.io/$DOCKERIO_USERNAME/$(/usr/bin/compose-service):$CONTAINER_VERSION
  when:
    branch:
    - main


- name: deploy
  failure: ignore
  environment:
    DRONE_SERVER:
      from_secret: server.drone.io
    DRONE_TOKEN:
      from_secret: token.drone.io
  commands:
  - /usr/bin/drone build create --branch main gautada/drone-container
  - /usr/bin/drone build create --branch main gautada/gitea-container
  - /usr/bin/drone build create --branch main gautada/postgresql-container
  when:
    branch:
    - main
    
trigger:
  event:
  - push

