#!/bin/sh
#
# health-check: This is the default health-check. All checks should default to
#               script.  This script attempts to call the base status check at
#               `/etc/container/status-check` and optionally tries to call
#               `/mnt/volumes/container/status-check` if the file exists to allow for
#               runtime checks to be defined.  Runtime status-check should only be used in
#               development.
# 
# author: adam@gautier.org
# date: 2022-11-16
# component: status
#
# - - - - - - - - - - - - - - - - - - - - - - -

STATUS_CHECK="/usr/bin/container-status-check"

if [ ! -f $STATUS_CHECK ] ; then
 echo "[ERROR] Unable to find default status check($STATUS_CHECK) script"
 return 1
fi

exec $STATUS_CHECK
RTN=$?
if [ $RTN -ne 0 ] ; then
 return $RTN
fi

# RUNTIME_STATUS_CHECK="/mnt/volumes/container/status-check"
# 
# exec $RUNTIME_STATUS_CHECK
# return $?
