#!/usr/bin/env python

# https-check: This python script attempts to *GET* the provided http url.  This script should fail if valid/successful 
#              response code is returned.

import requests # https://requests.readthedocs.io/en/latest/
import sys
from urllib.parse import urlparse

HTTP_REDIR_MVPERM = 301
HTTP_REDIR_PERM = 308
assert 2 == len(sys.argv), "Invalid parameters"
url = sys.argv[1]
scheme = urlparse(url).scheme
assert "http" == scheme, "URL scheme(%s) should be http" % scheme

response = requests.get(url, allow_redirects=False)
code = response.status_code 

print(url, code, response.content)
print(" - - - - - - ")
print(response.headers)
print()

if HTTP_REDIR_MVPERM == code or HTTP_REDIR_PERM == code: 
 location = response.headers['Location']
 lscheme = urlparse(location).scheme
 if "https" == lscheme:
  print("[SUCCESS] URL endpoint(%s) does redirect to https(%s)" % (url, location))  
  sys.exit(0)
 else:
  print("[FAIL] URL endpoint(%s) redirects to unknown scheme(%s)"  % (url, location))
  sys.exit(code)
else:
 print("[FAIL] URL endpoint(%s) returned a successful response code(%s)"  % (url, code))
 sys.exit(code)

