#!/bin/sh
#
# status-check: This is the default status check and should be called by all checks.
#
# author: adam@gautier.org
# date: 2022-11-16
# component: status
#

# Check - crond daemon - running is healthy
CMD="/usr/bin/pgrep crond"
$(echo $CMD) > /dev/null
RTN=$?
if [ $RTN -eq 1 ] ; then
 echo "[ERROR] Failed the status check($CMD)"
 return 1
fi

