#!/bin/sh
#
# version: This is a simple script to initialize the profile and allows for
#          `version` to return the container to work from the docker cli
#
# author: adam@gautier.org
# date: 2022-11-17
# component: version
#
# - - - - - - - - - - - - - - - - - - - - - - -

cat /etc/alpine-release
