---
name: "Continuous Integration: Build and Publish Multi-Architecture Image"
#FF=2
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main

jobs:
  ci-aarch64:
    uses: gautada/cicd/.github/workflows/ci-podman-arch.yaml@main
    with:
      architecture: aarch64
    secrets:
      REGISTRY_USERNAME: ${{ secrets.DOCKERIO_REGISTRY }}
      REGISTRY_TOKEN: ${{ secrets.DOCKERIO_TOKEN }}
