---
name: "Continuous Integration: Build and Publish Multi-Architecture Image"

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main

jobs:
  ci-aarch64:
    runs-on: ubuntu-latest
    uses: https://github.com/gautada/cicd/.github/workflows/ci-podman-arch.yml@main
    with:
      architecture: aarch64
