---
name: "Continuous Integration: Build and Publish Multi-Architecture Image"

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main

jobs:
  ci-aarch64:
    uses: https://github.com/gautada/cicd/.github/workflows/ci-podman-arch.yml@main
    with:
      architecture: aarch64
    secrets:
      REGISTRY_USERNAME: ${{ secrets.DOCKERIO_REGISTRY }}
      REGISTRY_TOKEN: ${{ secrets.DOCKERIO_TOKEN }}
