---
name: "Continuous Integration: Build and Publish Multi-Architecture Image"
#FF=6
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main

jobs:
  linter:
    uses: gautada/cicd/.github/workflows/ci-linter.yaml@main
  aarch64:
    needs: linter
    uses: gautada/cicd/.github/workflows/ci-podman-arch.yaml@main
    with:
      architecture: aarch64
    secrets:
      REGISTRY_USERNAME: ${{ secrets.DOCKERIO_REGISTRY }}
      REGISTRY_TOKEN: ${{ secrets.DOCKERIO_TOKEN }}
  amd64:
    needs: linter
    uses: gautada/cicd/.github/workflows/ci-podman-arch.yaml@main
    with:
      architecture: amd64
    secrets:
      REGISTRY_USERNAME: ${{ secrets.DOCKERIO_REGISTRY }}
      REGISTRY_TOKEN: ${{ secrets.DOCKERIO_TOKEN }}
