---
name: "Continuous Integration: Build and Publish Multi-Architecture Image"
# This is the generic reusable template for building containers

on:
  workflow_dispatch: {}
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main

jobs:
  linter:
    uses: gautada/cicd/.github/workflows/ci-linter.yaml@main
  clean:
    uses: gautada/cicd/.github/workflows/ci-registry-clean.yaml@main
    secrets:
      REGISTRY_USERNAME: ${{ secrets.DOCKERIO_REGISTRY }}
      REGISTRY_TOKEN: ${{ secrets.DOCKERIO_TOKEN }}
  build-arm64:
    needs: linter
    uses: gautada/cicd/.github/workflows/ci-podman-arch.yaml@main
    with:
      architecture: "arm64"
    secrets:
      REGISTRY_USERNAME: ${{ secrets.DOCKERIO_REGISTRY }}
      REGISTRY_TOKEN: ${{ secrets.DOCKERIO_TOKEN }}
  build-amd64:
    needs: linter
    uses: gautada/cicd/.github/workflows/ci-podman-arch.yaml@main
    with:
      architecture: "amd64"
    secrets:
      REGISTRY_USERNAME: ${{ secrets.DOCKERIO_REGISTRY }}
      REGISTRY_TOKEN: ${{ secrets.DOCKERIO_TOKEN }}
  integrate:
    needs: [arm64, amd64]
    uses: gautada/cicd/.github/workflows/ci-podman-dev.yaml@main
    with:
      architectures: '["build-arm64", "build-amd64"]'
    secrets:
      REGISTRY_USERNAME: ${{ secrets.DOCKERIO_REGISTRY }}
      REGISTRY_TOKEN: ${{ secrets.DOCKERIO_TOKEN }}
  release:
    needs: [integrate]
    uses: gautada/cicd/.github/workflows/cd-tag-latest.yaml@main
    secrets:
      REGISTRY_USERNAME: ${{ secrets.DOCKERIO_REGISTRY }}
      REGISTRY_TOKEN: ${{ secrets.DOCKERIO_TOKEN }}
